repos:
-   repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
    - id: black
      language_version: python3.9.13
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.13
    hooks:
    - id: flake8

-   repo: https://github.com/pre-commit/mirrors-isort
    rev: 'v5.6.4'
    hooks:
    -   id: isort
